### ISSUE TITLE
naming discussion

### ISSUE THREAD

**Issue by mr-git** [hseeberger/eventsourced#231]
I am not Rust developer, but I fail to understand why public API should have partial names?

I found in code import like:
```rust
evt_log::EvtLog, snapshot_store::SnapshotStore
```
Why omit 2 characters in words `event_log` and `EventLog`?

It is very strange, that word `EventSourced` is used instead of `EvtSourced` or worse: `EvtSrcd` or similar :)

**Comment by hseeberger** [comment]
The motivation was to make the many many occurrences of the words event (evt) and command (cmd) more lightweight. EventSourced is an exception, because it the project name, too.

Having said that, naming is hard. Maybe these abbreviations were not a good decision, but now they are written in stone, because it is – as you noticed – part of a public API.

**Comment by hseeberger** [comment]
I have been a Scala developer for more than a decade ;-)

I think that in "domains" some terms can be abbreviated and be well understood by humans, e.g. in event sourcing evt and cmd can be used. But nevertheless event and command are not much longer. BTW, it's not about typing, but about the ease of reading: very long names lead to worse readability, sometimes even to unnecessary line breaks.

Anyway, here we have an inconsistency btw. EventSourced and Evt. And I hate inconsistencies. So I will play with the renaming ...


Mareks Rampāns ***@***.***> schrieb am Donnerstag, 18. April 2024 um 15:44:

**Comment by hseeberger** [comment]
Fixed in #232.

**Comment by mr-git** [comment]
yay! I skimmed the diff - doesn't look like much changed, but consistency got improved! 👍 
Impressive

**Comment by hseeberger** [comment]
Not much changed?
<img width="777" alt="Bildschirmfoto 2024-04-19 um 16 54 43" src="https://github.com/hseeberger/eventsourced/assets/41911/e4206fe2-fb0f-4beb-a912-7b4d6a99853e">

**Comment by mr-git** [comment]
>Not much changed?

Content wise - not much
Consistency wise - a lot! :) 

Thank you!

Feel free to close it as part of your workflow.

**Comment by hseeberger** [comment]
You are welcome. Thanks for triggering me!

**Comment by hseeberger** [comment]
Fixed by #232.
